---
<% if fog_file = File.expand_path('~/.fog') and File.exists?(fog_file)
  fog_file = YAML.load_file(fog_file)
  ENV['AWS_ACCESS_KEY_ID'] ||= fog_file.fetch('travis-ci', {})['aws_access_key_id']
  ENV['AWS_SECRET_ACCESS_KEY'] ||= fog_file.fetch('travis-ci', {})['aws_secret_access_key']
  ENV['AWS_SSH_KEY_ID'] ||= fog_file.fetch('travis-ci', {})['aws_keypair_name']
  ENV['EC2_SSH_KEY_PATH'] ||= File.expand_path('~/.ssh/id_rsa_kitchen_ec2')
end %>
driver:
  require_chef_omnibus: "11.4.4"

provisioner:
  name: chef_solo
  attributes:
    test_kitchen: true
    rails_env: 'test'
    ssh_users: {}
    opsworks:
      ruby_version: '1.9.3'
      ruby_stack: "ruby"
      instance:
        id: "2d4446c7-2c8e-4a82-835c-8af1cc2793dc"
        hostname: "ngin-test-kitchen"
        instance_type: "t2.medium"
        public_dns_name: "localhost"
        private_dns_name: "localhost"
        ip: "127.0.0.1"
        private_ip: "127.0.0.1"
        architecture: "x86_64"
        layers:
          - "rails-passenger-app"
        backends: 8
        aws_instance_id: "i-75995884"
        region: "us-east-1"
        availability_zone: "us-east-1b"
        subnet_id: "subnet-f8196fd0"
        infrastructure_class: "ec2"
    nginx:
      custom_package:
        source: https://s3.amazonaws.com/sportngin-ops-files/nginx-1.8.0-passenger2.amzn1.ngx.x86_64.rpm
    deploy:
      test_app:
        ssl_support: true
        ssl_certificate: |
<%= File.read('test-kitchen.sportngin.com.crt').gsub(/^/, "            ") %>
        ssl_certificate_key: |
<%= File.read('test-kitchen.sportngin.com.key').gsub(/^/, "            ") %>
        ssl_certificate_ca: null
        application: "test_app"
        database: {}
        migrate: false
        deploy_to: "/srv/test-www/test_rack_app"
        environment: {}
        scm:
          scm_type: "other"
        rails_env: "test"
        auto_bundle_on_deploy: false
        environment_variables: {}
        restart_command: null
        symlinks:
          log: "log"
          system: "public/system"
          pids: "tmp/pids"
        deploying_user: null
        application_type: "other"
        memcached:
          port: 11211
          host: null
        symlink_before_migrate:
          config/database.yml: "config/database.yml"
          config/memcached.yml: "config/memcached.yml"
        sleep_before_restart: 0
        mounted_at: null
        domains:
          - "test-kitchen.sportngin.com"
        document_root: "public"

platforms:
  - name: amazon
    driver_plugin: ec2
    driver:
      instance_type: c3.large
      image_id: ami-0268d56a
      region: us-east-1
      availability_zone: us-east-1b
      security_group_ids: ['ci-testing']
      interface: public
      tags:
        Name: <%= "#{ENV['CI'] ? 'travis-ci' : ENV['USER']}-opsworks-passenger-kitchen" %>
        Env: public
    transport:
        ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>
        username: ec2-user

suites:
  - name: default
    run_list:
      - recipe[opsworks_initial_setup]
      - recipe[ssh_users]
      - recipe[dependencies]
      - recipe[opsworks-passenger::setup]
      - recipe[opsworks-passenger::test-setup]
      - recipe[opsworks-passenger::deploy]
    attributes:
      nginx:
        worker_rlimit_nofile: 4096
        default_site:
          enable: true
        restart_on_deploy: true

  - name: maintenance
    run_list:
      - recipe[opsworks_initial_setup]
      - recipe[ssh_users]
      - recipe[dependencies]
      - recipe[opsworks-passenger::setup]
      - recipe[opsworks-passenger::test-setup]
      - recipe[opsworks-passenger::deploy]
    attributes:
      nginx:
        default_site:
          enable: true
        serve_maintenance_page: true
        restart_on_deploy: true

  - name: multi_site_html_app
    run_list:
      - recipe[opsworks_initial_setup]
      - recipe[ssh_users]
      - recipe[dependencies]
      - recipe[opsworks-passenger::setup]
      - recipe[opsworks-passenger::test-setup]
      - recipe[opsworks-passenger::deploy]
    attributes:
      nginx:
        default_site:
          enable: true
        try_static_files: true
        default_server: true
        restart_on_deploy: true

  - name: no_restart_on_deploy
    run_list:
      - recipe[opsworks_initial_setup]
      - recipe[ssh_users]
      - recipe[dependencies]
      - recipe[opsworks-passenger::setup]
      - recipe[opsworks-passenger::test-setup]
      - recipe[opsworks-passenger::deploy]
    attributes:
      nginx:
        restart_on_deploy: false
