---
<% if fog_file = File.expand_path('~/.fog') and File.exists?(fog_file)
  fog_file = YAML.load_file(fog_file)
  ENV['AWS_ACCESS_KEY_ID'] ||= fog_file.fetch('travis-ci', {})['aws_access_key_id']
  ENV['AWS_SECRET_ACCESS_KEY'] ||= fog_file.fetch('travis-ci', {})['aws_secret_access_key']
  ENV['AWS_KEYPAIR_NAME'] ||= fog_file.fetch('travis-ci', {})['aws_keypair_name']
  ENV['EC2_SSH_KEY_PATH'] ||= File.expand_path('~/.ssh/id_rsa_kitchen_ec2')
end %>
driver:
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  aws_ssh_key_id: <%= ENV['AWS_KEYPAIR_NAME'] %>
  require_chef_omnibus: "11.4.4"
  availability_zone: us-east-1c
  associate_public_ip: true
  ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>
  username: ec2-user
  ebs_delete_on_termination: true
  image_id: ami-146e2a7c
  security_group_ids: ['sg-d3ed64b7']
  subnet_id: subnet-f0910b87
  interface: dns
  tags:
    Name: <%= "#{ENV['CI'] ? 'travis-ci' : ENV['USER']}-opsworks-passenger-kitchen" %>
    Env: public

provisioner:
  name: chef_solo
  attributes:
    test_kitchen: true
    rails_env: 'test'
    ssh_users: {}
    opsworks:
      ruby_version: '1.9.3'
      ruby_stack: "ruby"
    nginx:
      custom_package:
        source: https://s3.amazonaws.com/sportngin-packages/public/nginx-1.2.9-passenger1.amzn1.x86_64.rpm
    deploy:
      test_app:
        ssl_support: true
        ssl_certificate: |
<%= File.read('test-kitchen.sportngin.com.crt').gsub(/^/, "            ") %>
        ssl_certificate_key: |
<%= File.read('test-kitchen.sportngin.com.key').gsub(/^/, "            ") %>
        ssl_certificate_ca: null
        application: "test_app"
        database: {}
        migrate: false
        deploy_to: "/srv/test-www/test_rack_app"
        environment: {}
        scm:
          scm_type: "other"
        rails_env: "test"
        auto_bundle_on_deploy: false
        environment_variables: {}
        restart_command: null
        symlinks:
          log: "log"
          system: "public/system"
          pids: "tmp/pids"
        deploying_user: null
        application_type: "other"
        memcached:
          port: 11211
          host: null
        symlink_before_migrate:
          config/database.yml: "config/database.yml"
          config/memcached.yml: "config/memcached.yml"
        sleep_before_restart: 0
        mounted_at: null
        domains:
          - "test-kitchen.sportngin.com"
        document_root: "public"

platforms:
  - name: c4-8xl
    driver_plugin: ec2
    driver_config:
      ebs_optimized: true
      flavor_id: c4.8xlarge
#  - name: c3-8xl
#    driver_plugin: ec2
#    driver_config:
#      flavor_id: c3.8xlarge
#  - name: c4-4xl
#    driver_plugin: ec2
#    driver_config:
#      ebs_optimized: true
#      flavor_id: c4.4xlarge
#  - name: c3-4xl
#    driver_plugin: ec2
#    driver_config:
#      flavor_id: c3.4xlarge

suites:
  - name: default
    run_list:
      - recipe[opsworks_initial_setup]
      - recipe[ssh_users]
      - recipe[dependencies]
      - recipe[opsworks-passenger::setup]
      - recipe[opsworks-passenger::test-setup]
      - recipe[opsworks-passenger::deploy]
    attributes:
      nginx:
        default_site:
          enable: true
        restart_on_deploy: true

