env:
  global:
  - EC2_SSH_KEY_PATH: ec2.pem
  - secure: F0whuji3VPjOhDqVNYLu12KvdTa0ePHjG+O5CWCA7v69OJIIDnQWAfvHHzM9C0seYFoLcblfIWAvXcxA2Rl3AtVbuIYx1KaxCgzslw9IAYZv6dP1GSC+OjLSB1Q6vPfq8HRisXIMNmRGAkboGwjPYQYfl/F9padkatfbdxTSFr0=
  - secure: VxkpVDubci8ix7wTE4yf2iVy0mdnv7BYVWYJ6vdzdk97Nj+5lo3Vj2UG/p9C1ks7DSDko5WMdFzcJV/kpoSVtKDV5/3oBD241+MWZIUiIwzcNru0QQBgEQIu3eFLVUZ4ONWTi7W6WOYUicKrSnSd5YkkJ35I7MnvCOmm/mYZmBc=
  - secure: KhLHgXfYMnPhaoUHeTOVD8WDgH3yETxbGu7iqbMANavbFVFlAQ6QsIuWg0EWJd+tGWt+o/wx0PYnMSm5bMgSlD+rkaUVLMEFTHE7J5y7uGM2RQNHK42kxZyVnYNRL9vbqWiW6CUvr9SDuywnzMLwO31TGheRt9feDIioty4lm58=
before_install:
- openssl aes-256-cbc -K $encrypted_93abe1fff8ae_key -iv $encrypted_93abe1fff8ae_iv
  -in ec2.pem.enc -out ec2.pem -d
- chmod 600 ec2.pem
script: bundle exec kitchen test -d always
language: ruby
bundler_args: --without development --deployment --jobs=3 --retry=3
cache: bundler
